<<<<<<< HEAD
# Generated by Django 5.2 on 2025-06-22 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
=======
# Generated by Django 5.2 on 2025-05-29 13:05

import django.db.models.deletion
>>>>>>> c88ac103dbcd299eccaf81ac54a241438167ebfc
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> c88ac103dbcd299eccaf81ac54a241438167ebfc
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('session_name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('misc_memory', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CacheMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.JSONField(blank=True, default=dict)),
                ('chat_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache_memory', to='chat_app.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='MainMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='main_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chat_app.mainmemory'),
        ),
        migrations.CreateModel(
=======
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='chat_app.chatsession')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> c88ac103dbcd299eccaf81ac54a241438167ebfc
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_app.chatsession')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('chat_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_memory', to='chat_app.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='SubMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('chat_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_memory', to='chat_app.chatsession')),
            ],
        ),
=======
>>>>>>> c88ac103dbcd299eccaf81ac54a241438167ebfc
    ]
