# Generated by Django 5.2 on 2025-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pending_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
