# Generated by Django 5.2 on 2025-07-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatsession_pending_data_chatsession_pending_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submemory',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='pending_data',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='pending_intent',
        ),
        migrations.DeleteModel(
            name='SessionMemory',
        ),
        migrations.DeleteModel(
            name='SubMemory',
        ),
    ]
